FROM fedora

RUN dnf install -y make \
  autoconf \
  automake \
  dos2unix \
  ninja-build \
  gcc \
  gcc-c++ \
  gdb \
  clang-18 \
  cmake \
  rsync \
  tar \
  python \
  git \
  valgrind \
  llvm18 \
